services:
  ccbb-backend:
    build:
      context: ./Backend
      secrets:
        - django-private-key
      args:
        DJANGO_APP_URL: https://cyclecount.app
    environment:
      DJANGO_APP_URL: https://cyclecount.app
    ports:
      - 8000:8000
    depends_on:
      - ccbb-backup
    restart: always
    volumes:
      - db-data:/app/data
      - static-data:/app/staticfiles
    labels:
      - docker-volume-backup.stop-during-backup=true
    secrets:
      - django-private-key

  ccbb-webserver:
    build:
      context: ./WebServer
      args:
        SERVER_NAME: cyclecount.app
        VITE_DATABASE_URL: https://cyclecount.app/db
    environment:
      SERVER_NAME: cyclecount.app
      VITE_DATABASE_URL: https://cyclecount.app/db
    depends_on:
      - ccbb-backend
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - static-data:/app/staticfiles
    secrets:
      - generated-private-key
      - generated-public-key

  ccbb-backup:
    image: offen/docker-volume-backup:v2.40.0
    restart: always
    env_file: ./Backup/backup.env
    volumes:
      - db-data:/backup/db-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Backup/archive:/archive

secrets:
  django-private-key:
    file: ./django-private-key.txt
  generated-private-key: # SSL Private Key
    file: ./ssl-private-key.txt
  generated-public-key: # SSL Public Cert
    file: ./ssl-public-key.crt

volumes:
  db-data:
  static-data: