# Generated by Django 5.0.1 on 2024-01-11 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccbb_backend', '0002_rename_cycles_cycle_rename_warehouses_warehouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='cycles_id',
            new_name='cycle_id',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='warehouses_id',
            new_name='warehouse_id',
        ),
    ]
