# Generated by Django 5.0.1 on 2024-01-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccbb_backend', '0003_rename_cycles_id_cycle_cycle_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='parts',
            field=models.JSONField(max_length=50),
        ),
    ]
