# Generated by Django 5.0.1 on 2024-01-12 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccbb_backend', '0005_rename_warehouses_id_cycle_warehouse_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts_in_system',
            old_name='cycle_id',
            new_name='bin_id',
        ),
        migrations.RenameField(
            model_name='parts_present',
            old_name='cycle_id',
            new_name='bin_id',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='bin',
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cycle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccbb_backend.cycle')),
            ],
        ),
    ]
