# Generated by Django 5.0.1 on 2024-01-12 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccbb_backend', '0006_rename_cycle_id_parts_in_system_bin_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parts_in_system',
            new_name='PartsInSystem',
        ),
        migrations.RenameModel(
            old_name='Parts_present',
            new_name='PartsPresent',
        ),
        migrations.RenameField(
            model_name='partsinsystem',
            old_name='parts_in_system_id',
            new_name='partsInSystem_id',
        ),
        migrations.RenameField(
            model_name='partspresent',
            old_name='parts_present_id',
            new_name='partsPresent_id',
        ),
    ]
