# Generated by Django 5.0.1 on 2024-01-12 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccbb_backend', '0008_remove_partspresent_bin_id_presentpart_systempart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentpart',
            old_name='PresentPart_id',
            new_name='presentPart_id',
        ),
        migrations.RenameField(
            model_name='systempart',
            old_name='SystemPart_id',
            new_name='systemPart_id',
        ),
    ]
