# Generated by Django 5.0.1 on 2024-01-18 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ccbb_backend",
            "0010_rename_presentpart_id_presentpart_present_part_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cycle",
            name="warehouse_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ccbb_backend.warehouse",
            ),
        ),
    ]
