# Generated by Django 5.0.1 on 2024-01-18 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccbb_backend", "0011_alter_cycle_warehouse_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cycle",
            name="warehouse_id",
            field=models.ForeignKey(
                default=1980,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warehouse",
                to="ccbb_backend.warehouse",
            ),
            preserve_default=False,
        ),
    ]
