# Generated by Django 5.0.1 on 2024-01-18 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccbb_backend", "0012_alter_cycle_warehouse_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cycle",
            name="warehouse_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ccbb_backend.warehouse"
            ),
        ),
    ]
