# Generated by Django 5.0.1 on 2024-01-19 22:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ccbb_backend", "0013_alter_cycle_warehouse_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cycle",
            old_name="warehouse_id",
            new_name="warehouse",
        ),
    ]
