# Generated by Django 5.0.1 on 2024-01-19 23:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ccbb_backend", "0014_rename_warehouse_id_cycle_warehouse"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cycle",
            old_name="warehouse",
            new_name="warehouse_id",
        ),
    ]
