# Generated by Django 5.0.1 on 2024-03-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccbb_backend', '0016_remove_physicallymissingpart_warehouse_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicallymissingpart',
            name='location',
        ),
        migrations.RemoveField(
            model_name='systematicallymissingpart',
            name='location',
        ),
    ]
