# Generated by Django 5.0.1 on 2024-03-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccbb_backend', '0018_alter_physicallymissingpart_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='executed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
