# Generated by Django 5.0.1 on 2024-03-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccbb_backend", "0019_transaction_executed"),
    ]

    operations = [
        migrations.AddField(
            model_name="physicallymissingpart",
            name="location",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="systematicallymissingpart",
            name="location",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
