# Generated by Django 5.0.3 on 2024-07-14 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccbb_backend", "0021_cycle_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="PastCycle",
            fields=[
                ("past_cycle_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("date_completed", models.DateField()),
                ("bin_list", models.JSONField(default=[])),
                (
                    "warehouse_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ccbb_backend.warehouse",
                    ),
                ),
            ],
        ),
    ]
