# Generated by Django 5.0.3 on 2024-07-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccbb_backend", "0026_alter_pastcycle_bin_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pastcycle",
            name="bin_list",
            field=models.JSONField(default=list),
        ),
    ]
