# Generated by Django 5.0.7 on 2024-07-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccbb_backend", "0027_alter_pastcycle_bin_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="cycle",
            name="asignee",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pastcycle",
            name="asignee",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
