# Generated by Django 5.0.7 on 2024-07-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ccbb_backend", "0028_cycle_asignee_pastcycle_asignee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cycle",
            name="asignee",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="pastcycle",
            name="asignee",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
